--------- 1. Conteggio dei verbali trascritti, 
SELECT COUNT(*) AS TOTALE_VERBALI  FROM VERBALE 
 --2. Conteggio dei verbali trascritti raggruppati per anagrafe, 
SELECT NOME, COGNOME,
COUNT(VERBALE.ID_VERBALE) AS TOTALE_VERBALI
FROM ANAGRAFICA
JOIN
VERBALE ON ANAGRAFICA.ID_ANAGRAFICA = Verbale.FK_ID_ANAGRAFICA
GROUP BY 
ANAGRAFICA.ID_ANAGRAFICA, ANAGRAFICA.NOME, ANAGRAFICA.COGNOME
--3. Conteggio dei verbali trascritti raggruppati per tipo di violazione,
SELECT  DESCRIZIONE,

COUNT(VERBALE.ID_VERBALE) AS TOTALE
FROM VIOLAZIONE
JOIN
VERBALE ON VIOLAZIONE.ID_TIPO_VIOLAZIONE = Verbale.FK_ID_VIOLAZIONE
GROUP BY 
 VIOLAZIONE.DESCRIZIONE
-- 4. Totale dei punti decurtati per ogni anagrafe
SELECT NOME, COGNOME,
SUM(DECURTAMENTO_PUNTI) AS TOTALE_PUNTI_DECURTATI
FROM ANAGRAFICA
JOIN
VERBALE ON ANAGRAFICA.ID_ANAGRAFICA = VERBALE.FK_ID_ANAGRAFICA
GROUP BY
ANAGRAFICA.ID_ANAGRAFICA, ANAGRAFICA.NOME, ANAGRAFICA.COGNOME
 -- 5. Cognome, Nome, Data violazione, Indirizzo violazione, importo e punti decurtati per tutti gli anagrafici  residenti a Palermo, 
 SELECT CITTA, COGNOME, NOME, DATA_VIOLAZIONE, INDIRIZZO_VIOLAZIONE, IMPORTO, DECURTAMENTO_PUNTI AS TOTALE_PUNTI_DECURTATI
FROM ANAGRAFICA 
JOIN
VERBALE ON ANAGRAFICA.ID_ANAGRAFICA = VERBALE.FK_ID_ANAGRAFICA WHERE CITTA = 'Palermo'
GROUP BY
CITTA,COGNOME, NOME, DATA_VIOLAZIONE, INDIRIZZO_VIOLAZIONE, IMPORTO, DECURTAMENTO_PUNTI
--6. Cognome, Nome, Indirizzo, Data violazione, importo e punti decurtati per le violazioni fatte tra il febbraio 2009 e luglio 2009,
 SELECT DATA_VIOLAZIONE COGNOME, NOME, DATA_VIOLAZIONE, INDIRIZZO_VIOLAZIONE, IMPORTO, DECURTAMENTO_PUNTI AS TOTALE_PUNTI_DECURTATI
FROM ANAGRAFICA 
JOIN
VERBALE ON ANAGRAFICA.ID_ANAGRAFICA = VERBALE.FK_ID_ANAGRAFICA WHERE DATA_VIOLAZIONE BETWEEN '2009-02-01' AND '2009-07-31'
GROUP BY
DATA_VIOLAZIONE,COGNOME, NOME, DATA_VIOLAZIONE,  INDIRIZZO_VIOLAZIONE, IMPORTO, DECURTAMENTO_PUNTI
--7. Totale degli importi per ogni anagrafico, 
 SELECT COGNOME, NOME,IMPORTO 
FROM ANAGRAFICA 
JOIN
VERBALE ON ANAGRAFICA.ID_ANAGRAFICA = VERBALE.FK_ID_ANAGRAFICA ORDER BY COGNOME
--8.Visualizzazione di tutti gli anagrafici residenti a Palermo
SELECT NOME, COGNOME FROM ANAGRAFICA WHERE CITTA ='Palermo'

--9. Query parametrica che visualizzi Data violazione, Importo e decurta mento punti relativi ad una certa data

DECLARE @DATA_SPECIFICA_VIOLAZIONE DATE = '2022-06-25';
SELECT DATA_VIOLAZIONE,IMPORTO,DECURTAMENTO_PUNTI
FROM VERBALE
WHERE DATA_VIOLAZIONE = @DATA_SPECIFICA_VIOLAZIONE;

--10. Conteggio delle violazioni contestate raggruppate per Nominativo dell’agente di Polizia, 
SELECT  NOMINATIVO_AGENTE,
COUNT(VIOLAZIONE.ID_TIPO_VIOLAZIONE) AS TOTALE
FROM VIOLAZIONE
JOIN
VERBALE ON VIOLAZIONE.ID_TIPO_VIOLAZIONE = Verbale.FK_ID_VIOLAZIONE
GROUP BY 
 NOMINATIVO_AGENTE
 --11. Cognome, Nome, Indirizzo, Data violazione, Importo e punti decurtati per tutte le violazioni che superino il decurtamento di 5 punti
 SELECT  COGNOME, NOME, DATA_VIOLAZIONE, INDIRIZZO_VIOLAZIONE, IMPORTO, DECURTAMENTO_PUNTI ,
 SUM(DECURTAMENTO_PUNTI)AS TOTALE_PUNTI_DECURTATI
FROM ANAGRAFICA 
JOIN
VERBALE ON ANAGRAFICA.ID_ANAGRAFICA = VERBALE.FK_ID_ANAGRAFICA WHERE DECURTAMENTO_PUNTI > 2 ---> ho abbassato da 5 a 2 per selezionare più campi
GROUP BY
COGNOME, NOME, DATA_VIOLAZIONE,  INDIRIZZO_VIOLAZIONE, IMPORTO, DECURTAMENTO_PUNTI
--12. Cognome, Nome, Indirizzo, Data violazione, Importo e punti decurtati per tutte le violazioni che superino l’importo di 400 euro.
 SELECT  COGNOME, NOME,  INDIRIZZO_VIOLAZIONE, DATA_VIOLAZIONE,IMPORTO, DECURTAMENTO_PUNTI ,
 SUM(IMPORTO)AS TOTALE_IMPORTO
FROM ANAGRAFICA 
JOIN
VERBALE ON ANAGRAFICA.ID_ANAGRAFICA = VERBALE.FK_ID_ANAGRAFICA WHERE IMPORTO > 200 ---> ho abbassato da 400 a 200 poichè avevo compilato cifre più basse
GROUP BY
COGNOME, NOME, DATA_VIOLAZIONE,  INDIRIZZO_VIOLAZIONE, IMPORTO, DECURTAMENTO_PUNTI





